# Generated by Django 3.1 on 2020-09-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('summary', models.TextField(max_length=1028)),
                ('main_contact', models.CharField(max_length=128)),
                ('main_contact_phone', models.IntegerField()),
                ('main_contact_email', models.CharField(max_length=64)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('link', models.URLField()),
                ('deal_validity', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
