# Generated by Django 3.1 on 2020-09-03 13:26

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterField(
            model_name='partners',
            name='main_contact_phone',
            field=phone_field.models.PhoneField(help_text='Main Contact Phone Number', max_length=31),
        ),
    ]
