# Generated by Django 3.1 on 2020-09-18 19:10

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0004_auto_20200821_1504'),
        ('user_profile', '0003_auto_20200828_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=128)),
                ('billing_address', models.CharField(max_length=256)),
                ('billing_postcode', models.CharField(max_length=15)),
                ('billing_city', models.CharField(max_length=32)),
                ('billing_country', django_countries.fields.CountryField(max_length=2)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='user_profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('line_item_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programs')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='purchase.checkout')),
            ],
        ),
    ]
