# Generated by Django 3.1 on 2020-09-05 16:47

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0003_auto_20200828_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_address', models.CharField(max_length=256)),
                ('billing_postcode', models.CharField(max_length=15)),
                ('billing_city', models.CharField(max_length=32)),
                ('billing_country', django_countries.fields.CountryField(max_length=2)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
            ],
        ),
    ]
