# Generated by Django 3.1 on 2020-09-08 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20200821_1504'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='program_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.programs'),
        ),
    ]
