# Generated by Django 3.1 on 2020-09-12 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0003_auto_20200908_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='program_id',
            new_name='program',
        ),
        migrations.AddField(
            model_name='checkout',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='order_number',
            field=models.CharField(default='', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
