# Generated by Django 3.1 on 2020-09-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20200912_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='profile',
            new_name='user',
        ),
        migrations.AddField(
            model_name='checkout',
            name='email',
            field=models.EmailField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
