# Generated by Django 3.1 on 2020-09-13 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20200828_0853'),
        ('purchase', '0006_auto_20200912_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile'),
        ),
    ]
