# Generated by Django 3.1 on 2020-09-14 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_auto_20200914_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 18, 43, 44, 451835, tzinfo=utc), editable=False),
        ),
    ]
