# Generated by Django 3.1 on 2020-09-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_auto_20200914_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='cost',
            new_name='program_cost',
        ),
        migrations.AddField(
            model_name='checkout',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
        ),
    ]
