# Generated by Django 3.1 on 2020-09-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20200821_1504'),
        ('purchase', '0014_auto_20200917_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='program_cost',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='CheckoutLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programs')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='purchase.checkout')),
            ],
        ),
    ]
