# Generated by Django 3.1 on 2020-09-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_auto_20200917_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='program',
        ),
    ]
