# Generated by Django 3.1 on 2020-09-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_auto_20200917_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutlineitem',
            name='line_item_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
