# Generated by Django 3.1 on 2020-09-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0019_checkoutlineitem_line_item_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutlineitem',
            name='line_item_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
        ),
    ]
