# Generated by Django 3.1 on 2020-09-17 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20200821_1504'),
        ('purchase', '0021_auto_20200917_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutlineitem',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programs'),
        ),
    ]
