# Generated by Django 3.1 on 2020-09-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0023_auto_20200917_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutlineitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
