# Generated by Django 3.1 on 2020-08-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20200823_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
