# Generated by Django 3.1 on 2020-08-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programs',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
