# Generated by Django 3.1 on 2020-08-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20200821_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programs',
            options={'verbose_name_plural': 'Programs'},
        ),
    ]
