# Generated by Django 3.1 on 2020-08-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name_plural': 'Testimonials'},
        ),
    ]
