# Generated by Django 3.1 on 2020-08-31 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20200821_1504'),
        ('testimonials', '0004_auto_20200830_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='program_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.programs'),
        ),
    ]
