# Generated by Django 3.1 on 2020-09-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0005_testimonials_program_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='score',
            field=models.PositiveIntegerField(choices=[[0, 0], [1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8], [9, 9], [10, 10]], default=0),
        ),
    ]
