# Generated by Django 3.1 on 2020-09-15 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0004_auto_20200821_1504'),
        ('testimonials', '0006_auto_20200903_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='program_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.programs'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
